name: sfcvm211-ucvm-ci

on:
  push:
    branches: [ main ]
##    branches: [ foofoo ]

jobs:
  sfcvm211-build-ucvm-linux:
#    needs: [sfcvm211-build-ucvm-mac]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - name: set UCVM_SRC_PATH 
      run: echo "UCVM_SRC_PATH=$RUNNER_WORKSPACE/sfcvm211/ucvm" >> $GITHUB_ENV
    - name: set UCVM_INSTALL_PATH 
      run: echo "UCVM_INSTALL_PATH=$RUNNER_WORKSPACE/sfcvm211/target" >> $GITHUB_ENV
    - name: load python pkgs
      run: (python3 -m pip install scipy h5py numpy pandas pybind11)
      shell: bash
### build ucvm(main) first 
    - name: get-ucvm 
      uses: actions/checkout@v6
      with: 
        repository: 'SCECcode/UCVM'
        ref: main
        path: ucvm
    - id: build-ucvm
      name: build ucvm
      uses: ./ucvm/.github/actions/build-ucvm-action
      with:
         initiating-repo: 'sfcvm211'
         target-model: 'sfcvm211'
         target-branch: 'main'
    - name: move stock sfcvm211 away
      run: (rm -rf $RUNNER_WORKSPACE/sfcvm211/ucvm/work/model/sfcvm211)
      shell: bash
### build sfcvm211 from github 
    - name: checkout sfcvm211 main
      uses: actions/checkout@v4
      with: 
        path: sfcvm211
    - name: move it to the right location
      run: (mv sfcvm211 $RUNNER_WORKSPACE/sfcvm211/ucvm/work/model; pwd; ls)
      shell: bash
    - name: build sfcvm211 as part of ucvm 
      run: (cd $RUNNER_WORKSPACE/sfcvm211/ucvm/work/model/sfcvm211; ./.github/scripts/sfcvm211-build.sh)
      shell: bash
#    - name: Start SSH debug with upterm for sfcvm211 github
#      if: ${{ failure() }}
#      uses: owenthereal/action-upterm@v1
#      with:
#        limit-access-to-actor: true
#        wait-timeout-minutes: 60
#    - name: sleep to keep runner alive
#      run: sleep 3600
### check ucvm is still valid
    - name: check on ucvm
      run: (source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ucvm_query -H)
      shell: bash
#    - name: Start SSH debug with upterm for sfcvm211 github
#      uses: owenthereal/action-upterm@v1
#      with:
#        limit-access-to-actor: true
#        wait-timeout-minutes: 60
#    - name: sleep to keep runner alive
#      run: sleep 3600
    - name: test sfcvm211 with ucvm
      run: (cd $RUNNER_WORKSPACE/sfcvm211/ucvm/work/model/sfcvm211; source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ./.github/scripts/sfcvm211-test-ucvm.sh)
      shell: bash
    - name: test sfcvm211 under ucvm
      run: (cd $RUNNER_WORKSPACE/sfcvm211/ucvm; source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ./.github/scripts/ucvm-test.sh)
      shell: bash

## Needs some tweaks to get geomodelgrids to install on MacOS
  sfcvm211-build-ucvm-mac:
    if: false ## skip this one
#    if: ${{ success() }}
#    needs: [sfcvm211-build-ucvm-linux]
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - name: set UCVM_SRC_PATH 
      run: echo "UCVM_SRC_PATH=$RUNNER_WORKSPACE/sfcvm211/ucvm" >> $GITHUB_ENV
    - name: set UCVM_INSTALL_PATH 
      run: echo "UCVM_INSTALL_PATH=$RUNNER_WORKSPACE/sfcvm211/target" >> $GITHUB_ENV
    - name: load python pkgs
      run: (pipx install --include-deps scipy h5py numpy pandas pybind11)
      shell: bash
### build ucvm(main) first 
    - name: get-ucvm 
      uses: actions/checkout@v4
      with: 
        repository: 'SCECcode/UCVM'
        ref: main
        path: ucvm
    - id: build-ucvm
      name: build ucvm
      uses: ./ucvm/.github/actions/build-ucvm-action
      with:
         initiating-repo: 'sfcvm211'
         target-model: 'sfcvm211'
         target-branch: 'main'
    - name: Start SSH debug with upterm for sfcvm211 github
      uses: owenthereal/action-upterm@v1
      with:
        limit-access-to-actor: true
        wait-timeout-minutes: 60
    - name: sleep to keep runner alive
      run: sleep 3600
    - name: move stock sfcvm211 away
      run: (rm -rf $RUNNER_WORKSPACE/sfcvm211/ucvm/work/model/sfcvm211)
      shell: bash
### build sfcvm211 from github 
    - name: checkout sfcvm211 main
      uses: actions/checkout@v4
      with: 
        path: sfcvm211
    - name: move it to the right location
      run: (mv sfcvm211 $RUNNER_WORKSPACE/sfcvm211/ucvm/work/model; pwd; ls)
      shell: bash
    - name: build sfcvm211 as part of ucvm 
      run: (cd $RUNNER_WORKSPACE/sfcvm211/ucvm/work/model/sfcvm211; ./.github/scripts/sfcvm211-build.sh)
      shell: bash
### check ucvm is still valid
    - name: check on ucvm
      run: (source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ucvm_query -H)
      shell: bash
    - name: test sfcvm211 with ucvm
      run: (cd $RUNNER_WORKSPACE/sfcvm211/ucvm/work/model/sfcvm211; source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ./.github/scripts/sfcvm211-test-ucvm.sh)
      shell: bash
    - name: test sfcvm211 under ucvm
      run: (cd $RUNNER_WORKSPACE/sfcvm211/ucvm; source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ./.github/scripts/ucvm-test.sh)
      shell: bash





